### PR TITLE
Bug 2037903: Alibaba Cloud not required credReqDir in command delete-ram-users

### LINKED ISSUE #437: Alibaba Cloud: delete-ram-user requires the credentials-requests
Summary:

When running the removal of ram users the `ccoctl` command requires the original `--credentials-requests` directory. This might be an issue when customers remove them after a cluster install. Having to preserve the original release payload or preserving the credentials requests becomes cumbersome.

Example:
```
~/go/src/github.com/openshift/cloud-credential-operator/ccoctl alibabacloud  delete-ram-users --region us-east-1 --name test-nsrlt   --credentials-requests-dir ~/tmp/alibaba/crs
```

Would it be possible to update the `delete-ram-users` command to use only the `--name <cluster_id>` parameter data to remove credentials? This would greatly simplify the process of removing credentials from a customer's standpoint and for the CI.

cc @DahuK

### PR DESCRIPTION
**Pull request by DahuK**
Alibaba Cloud: support not required input credentials-requests-dir in command delete-ram-users
Fixes #437

### CODE REVIEW

**Comment by DahuK** [comment]
@kwoodson please help to review this, thanks a lot!

File: pkg/cmd/provisioning/alibabacloud/create-ram-users.go [hunk 1]
```diff
@@ -37,6 +37,8 @@ type: Opaque`
 	ramPolicyType = "Custom"
 	// autoRotateStrategy will delete the earliest inactive policy version
 	autoRotateStrategy = "DeleteOldestNonDefaultVersionWhenLimitExceeded"
+	// ccoctlResourceTagKeyPrefix is the prefix of the tag key applied to the AWS resources created/shared by ccoctl
+	ccoctlResourceTagKeyPrefix = "openshift.io/ccoctl"
```
Comment (joelddiaz) [inline pkg/cmd/provisioning/alibabacloud/create-ram-users.go:41]: The variable name indicates that this is related to tagging a resource. From looking at the code, this string is simply being used to place a comment/note on the RAM User details. Also, the comment for this variable talks about AWS.

File: pkg/cmd/provisioning/alibabacloud/delete-ram-users.go [hunk 2]
```diff
@@ -89,15 +89,42 @@ func deleteComponentUser(client alibabacloud.Client, userName string) error {
 	return err
 }
 
+func getUsersToDelete(client alibabacloud.Client, name, credReqDir string) ([]string, error) {
+	usersToDelete := make([]string, 0)
+	if credReqDir != "" {
+		// Process directory
+		credRequests, err := provisioning.GetListOfCredentialsRequests(credReqDir)
```
Comment (joelddiaz) [inline pkg/cmd/provisioning/alibabacloud/delete-ram-users.go:96]: I thought the purpose of this PR was to not need the `credReqDir` to be provided in the `delete` subcommand?

File: pkg/cmd/provisioning/alibabacloud/create-ram-users.go (hunk 1 above)
Comment (DahuK) [reply pkg/cmd/provisioning/alibabacloud/create-ram-users.go:41]: fixed the comment, thanks for the finding! and the comment is used in delete command to find out which user should be removed if no credReqDir given

Comment (joelddiaz) [reply pkg/cmd/provisioning/alibabacloud/create-ram-users.go:41]: This still calls the variable \*TagKeyPrefix\*. I think it would be more clear to remove any reference to "Tag" as AliCloud doesn't presently allow tagging RAM Users. Maybe something like `ccoctlResourcePrefix` or `ccoctlResourceCommentPrefix`?

File: pkg/cmd/provisioning/alibabacloud/delete-ram-users.go (hunk 2 above)
Comment (joelddiaz) [reply pkg/cmd/provisioning/alibabacloud/delete-ram-users.go:96]: I'd rather just delete the `credReqDir` since finding the resource(s) by using the `--name` parameter should be sufficient for finding the resources that need to be cleaned up. And the `--name` parameter is already required, so we already have all the information needed to do a proper cleanup.

Comment (DahuK) [reply pkg/cmd/provisioning/alibabacloud/delete-ram-users.go]: ok, have removed the `credReqDir`

File: pkg/cmd/provisioning/alibabacloud/create-ram-users.go (hunk 1 above)
Comment (DahuK) [reply pkg/cmd/provisioning/alibabacloud/create-ram-users.go]: got it, change the variable to `ccoctlResourcePrefix`

**Review by joelddiaz — COMMENTED** [review]
/lgtm
